# Example Unit Testing Script
expect_that(1, equals(1))

# Create a Test A test encapsulates a series of expectations about small, 
# self-contained set of functionality. 
# Each test is contained in a context and 
# contains multiple expectation generated by expect_that.
test_that("trigonometric functions match identities", {
  expect_that(sin(pi / 4), equals(1/sqrt(2)))
})
# test_that("this test fails", fail())

# Check that the source data has the expected format
# test_that("data has loaded as expected", {
#   expect_that(length(local.reviews),              equals(5))
#   expect_that(length(outdoor.furniture.assets),   equals(8))
#   expect_that(licenced.premises$LicenceNo,        is_a("integer"))
#   expect_that(location.info$zip,                  is_a("character"))
# })
